name: echo-hello

on: push 

jobs:
  echo-hello: 
    runs-on: ubuntu-latest 
    steps:
      - name: hello world with echo 
        run: echo Hello World!

      - name: hello world with cli
        run: python -c "print('Hello World!')"

      - name: python version check
        run: python --version

      - name: python version upgrade (3.9)
        run: sudo apt install python3.9

      - name: python version check
        run: python3.9 --version
